# Generated by Django 2.1.4 on 2019-06-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20190609_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtContent',
            new_name='ArtChapter',
        ),
    ]
