# Generated by Django 2.1.4 on 2019-05-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20190527_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcontent',
            name='chapter_add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
