# Generated by Django 2.1.4 on 2019-06-21 17:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20190614_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artchapter',
            name='chapter_content',
            field=tinymce.models.HTMLField(verbose_name='文章内容'),
        ),
    ]
