# Generated by Django 2.1.4 on 2019-06-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20190621_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artchapter',
            options={'ordering': ['chapter_add_date']},
        ),
    ]
