# Generated by Django 2.1.4 on 2019-08-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20190621_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['art_add_date']},
        ),
    ]
