# Generated by Django 2.1.4 on 2019-06-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20190531_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcontent',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Article', verbose_name='文章'),
        ),
    ]
