# Generated by Django 2.1.4 on 2019-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20190809_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_type',
            field=models.CharField(choices=[('popu', '流行'), ('classics', '经典')], max_length=20, verbose_name='类型'),
        ),
    ]
