# Generated by Django 2.1.4 on 2019-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20190814_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_type',
            field=models.CharField(choices=[('流行', 'liuxing'), ('经典', 'jingdian')], max_length=20),
        ),
    ]
