# Generated by Django 2.1.4 on 2019-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_auto_20190814_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_type',
            field=models.CharField(choices=[('流行', ('玄幻', '奇幻', '科幻', '武侠', '仙侠', '都市', '言情', '历史')), ('经典', 'jingdian')], max_length=20),
        ),
    ]
