# Generated by Django 2.1.4 on 2019-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_auto_20190814_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_type',
            field=models.CharField(choices=[('流行', {'仙侠', '科幻', '玄幻', '奇幻', '言情', '武侠', '都市', '历史'}), ('经典', 'jingdian')], max_length=20),
        ),
    ]
