# Generated by Django 2.1.4 on 2019-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0016_auto_20190815_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_type',
            field=models.CharField(choices=[('流行', (('xuanhuan', '玄幻'), ('qihuan', '奇幻'), ('kehuan', '科幻'), ('wuxia', '武侠'), ('xianxia', '仙侠'), ('dushi', '都市'), ('yanqing', '言情'), ('lishi', '历史'))), ('经典', (('mingzhu', '名著'), ('shenhua', '神话'), ('xiaoshuo', '小说'), ('zhuzi', '诸子'), ('shici', '诗词'), ('shishu', '史书')))], max_length=200),
        ),
    ]
